grails-app/domain/com/nexusug/xlsform/reporting/Report.groovy
package com.nexusug.xlsform.reporting

class Report {
	String name
	String description
	boolean archived

	List<Condition> conditions
	List<ConditionLinker> conditionLinkers
	List<DisplayColumn> displayColumns
	String formLinkerQuestion

	static hasMany = [conditions: Condition, conditionLinkers: ConditionLinker, displayColumns: DisplayColumn]

	static constraints = {
		formLinkerQuestion nullable: true
		description nullable: true
		conditions nullable: false
		conditionLinkers nullable: true, validator: { val, report ->
			int conditionSize = report.conditions ? report.conditions.size() : 0
			int conditionLinkerSize = val ? val.size() : 0
			if (conditionSize > 1 && conditionSize - conditionLinkerSize != 1) {
				return 	['count.invalid']
			}
		}
	}

	static mapping = {
		version false
	}

	@Override
	public String toString() {
		return "Report{" +
				"id=" + id +
				", name='" + name + '\'' +
				", description='" + description + '\'' +
				", conditions=" + conditions +
				", conditionLinkers=" + conditionLinkers +
				", displayColumns=" + displayColumns +
				", formLinkerQuestion='" + formLinkerQuestion + '\'' +
				", version=" + version +
				'}';
	}
}

grails-app/controllers/com/nexusug/xlsform/ReportController.groovy
package com.nexusug.xlsform

import com.nexusug.xlsform.display.model.XformDisplayModel
import com.nexusug.xlsform.display.util.XformReader
import com.nexusug.xlsform.reporting.ConditionLinker
import com.nexusug.xlsform.reporting.ConditionOperator
import com.nexusug.xlsform.reporting.Report
import com.nexusug.xlsform.reporting.ReportEntry
import grails.converters.JSON
import grails.transaction.Transactional
import groovy.json.JsonBuilder

import static org.springframework.http.HttpStatus.CREATED
import static org.springframework.http.HttpStatus.UNPROCESSABLE_ENTITY
import static org.springframework.http.HttpStatus.NOT_FOUND

@Transactional(readOnly = true)
class ReportController {
	ReportManagementService reportManagementService

	def index() {

	}

	def list() {
		withFormat {
			'*' {
				respond Report.findAllWhere(archived: false)
			}
		}
	}

	def view(Report report) {
		if (report == null) {
			notFound()
			return
		}
		respond report
	}

	def edit(Report report) {
		if (report == null) {
			notFound()
			return
		}
		Map model = reportCreationModel()

		model.reportJsonModel = report as JSON
		println model.reportJsonModel
		respond report, model: model
	}

	@Transactional
	def delete(Report report) {
		if (report == null) {
			notFound()
			return
		}
		report.archived = true
		report.save(failOnError: true, flush: true)
		flash.message = g.message(code: 'report.delete.success.message', args: [report.name])
		redirect action: 'index'
	}

	def submissions(Report report) {
		if (report == null) {
			notFound()
			return
		}
		List<ReportEntry> reportEntries = reportManagementService.generateReport(report)
		respond reportEntries
	}

	def create() {
		respond new Report(params), model: reportCreationModel()
	}

	/**
	 * Helper method for returns properties needed typically when creating a new report.
	 * @return
	 */
	private static Map reportCreationModel() {
		List<XformDisplayModel> formDisplayModels = []
		Map<String, String> allFormsXlsIdModelMap = [:]

		Xform.all?.each { Xform form ->
			XformDisplayModel formDisplayModel = new XformDisplayModel()
			formDisplayModel.name = form.name
			formDisplayModel.title = form.title
			formDisplayModel.xlsId = form.xlsId
			formDisplayModel.displayables = XformReader.getFormElements(form.formXml)

			formDisplayModels.add(formDisplayModel)
			allFormsXlsIdModelMap.put(form.xlsId, XformReader.serializeFormModelToJSON(form.formXml, 0))
		}
		def conditionOperators = [:]
		conditionOperators['decimal'] = ConditionOperator.values().findAll { it.canValidate('1.0') && !it.name().startsWith('TEXT') }.collect {
			[text: it.userFriendlyName(), value: it.name()]
		}
		conditionOperators['integer'] = ConditionOperator.values().findAll { it.canValidate('1') && !it.name().startsWith('TEXT')}.collect {
			[text: it.userFriendlyName(), value: it.name()]
		}
		conditionOperators['text'] = ConditionOperator.values().findAll { it.canValidate('text') }.collect {
			[text: it.userFriendlyName(), value: it.name()]
		}

		Map model = [
				formDisplayModelsJson: new JsonBuilder(formDisplayModels).toString(),
				allFormsXlsIdModelMap: new JsonBuilder(allFormsXlsIdModelMap).toString(),
				conditionLinkers     : ConditionLinker.values()*.name() as JSON,
				conditionOperators   : conditionOperators as JSON
		]
		return model
	}

	@Transactional
	def saveOrUpdate(Report report) {
		if (report.hasErrors()) {
			withFormat {
				html {
					render report.errors, view: 'create'
				}
				'*' {
					response.status = UNPROCESSABLE_ENTITY.value()
					respond report
				}
			}
		} else {
			handleBelongsToAssociationGotcha(report)
			if (report.id) {
				reportManagementService.updateReport(report)
			} else {
				report.save(flush: true, failOnError: true)
			}
			withFormat {
				html {
					flash.message = message(code: 'default.created.message', args: [message(code: 'report.label', default: 'report'), report.id])
					redirect report
				}
				'*' { render status: CREATED }
			}
		}
	}

	/**
	 * This method exists due to a bug that can vaguely be explained by
	 * <a href="https://github.com/robfletcher/grails-gson#cascading-saves">cascading-saves gotcha in gson lib</a>
	 * @param report the report whose children with belongsTo annotation are to be assigned the report manually.
	 */
	private void handleBelongsToAssociationGotcha(Report report) {
		report.conditions?.each {
			it.report = report
		}
		report.displayColumns?.each {
			it.report = report
		}
	}

	protected void notFound() {
		//todo this doesn't seem to work, needs to be fixed
		withFormat {
			html {
				flash.message = message(code: 'default.not.found.message', args: [
						message(code: 'report.label', default: 'report'),
						params.id
				])
				redirect action: "index"
			}
			'*' { render status: NOT_FOUND }
		}
	}
}

grails-app/views/report/_report_form_content.gsp
<input type="hidden" data-value="${formDisplayModelsJson}" id="report-creation-config" name="report-creation-config" readonly />
<input type="hidden" data-value="${allFormsXlsIdModelMap}" id="allFormsXlsIdModelMap" name="allFormsXlsIdModelMap" readonly />
<input type="hidden" data-value="${reportJsonModel}" id="saveReportDetails" name="saveReportDetails" readonly />
<input type="hidden" name="id" value="${reportInstance?.id}" />
<input type="hidden" id="conditionOperators" name="conditionOperators" data-value="${conditionOperators}" readonly />
<input type="hidden" id="conditionLinkers" name="conditionLinkers" data-value="${conditionLinkers}" readonly />
<div class="form-horizontal">
	<div class="form-group">
		<label for="name" class="col-sm-2 control-label">Name</label>

		<div class="col-sm-10">
			<input type="text" required class="form-control" id="name" name="name" value="${reportInstance?.name}" placeholder="name of the report">
		</div>
	</div>

	<div class="form-group">
		<label for="description" class="col-sm-2 control-label">Description</label>

		<div class="col-sm-10">
			<input type="text" class="form-control" id="description" name="description" value="${reportInstance?.description}"
				   placeholder="description og the report">
		</div>
	</div>
</div>
<div class="panel panel-default">
	<div class="panel-heading">Conditions</div>
	<div class="panel-body conditions-holder" id="conditions-holder"></div>
</div>
<div class="panel panel-default">
	<div class="panel-heading">Fields to display</div>
	<div class="panel-body">
		<div class="col-md-6" id="report-column-creator-holder"></div>
		<div class="col-md-6">
			<div class="panel panel-default">
				<div class="panel-heading">
					Columns to be displayed
				</div>
				<div class="panel-body" id="report-display-cols"></div>
			</div>
		</div>
	</div>
</div>

grails-app/views/report/_side-nav.gsp
<ul class="nav nav-tabs nav-justified report-context-nav">
	<li role="presentation" class="${actionName in ['index', 'view', 'edit'] ? 'active' : ''}">
		<g:link controller="report" action="index">View reports</g:link>
	</li>
	<li role="presentation" class="${params.action == 'create' ? 'active' : ''}">
		<g:link controller="report" action="create">Create report</g:link>
	</li>
</ul>

grails-app/views/report/create.gsp
<g:applyLayout name="one-column-top-nav">
	<head>
		<title>reports</title>
		<asset:javascript src="reports-manifest.js"/>
		<asset:stylesheet src="reports-manifest.css"/>
		<asset:javascript src="reports/report-builder.js"/>
		<g:render template="/handlebars/reporting" />
	</head>
	<content tag="top-nav">
		<g:render template="side-nav"/>
	</content>
	<content tag="main">
		<g:form action="saveOrUpdate">
			<g:render template="report_form_content"/>
			<button type="submit" class="btn btn-default btn-sm" id="submit" value="create">Submit</button>
		</g:form>
	</content>
</g:applyLayout>

grails-app/views/report/edit.gsp
<g:applyLayout name="one-column-top-nav">
	<head>
		<title>reports</title>
		<asset:javascript src="reports-manifest.js"/>
		<asset:stylesheet src="reports-manifest.css"/>
		<asset:javascript src="reports/report-builder.js"/>
		<g:render template="/handlebars/reporting"/>
	</head>
	<content tag="top-nav">
		<g:render template="side-nav"/>
	</content>
	<content tag="main">
		<ol class="breadcrumb">
			<li><g:link controller="report">Reports</g:link></li>
			<li><g:link controller="report" action="edit" id="${reportInstance?.id}">Edit</g:link></li>
			<li class="active ">${reportInstance?.name}</li>
		</ol>
		<g:form action="saveOrUpdate">
			<g:render template="report_form_content"/>
			<button type="submit" class="btn btn-default btn-sm" id="submit" value="update">Submit</button>
		</g:form>
	</content>
</g:applyLayout>

grails-app/views/report/index.gsp
<g:applyLayout name="one-column-top-nav">
	<head>
		<title>forms</title>
		<asset:javascript src="reports-manifest.js"/>
		<asset:stylesheet src="reports-manifest.css"/>
		<g:render template="/handlebars/reporting"/>
		<asset:javascript src="/reports/report-viewer.js"/>
	</head>
	<content tag="top-nav">
		<g:render template="side-nav"/>
	</content>
	<content tag="main">
		<table id="reports-list"
			   data-toggle="table"
			   data-url="${g.createLink(controller: 'report', action: 'list')}.json"
			   data-striped="true"
			   data-detail-view="true"
			   data-detail-formatter="reportViewer.reportDetailsFormatter">
			<thead>
			<tr>
				<th data-field="name">Created reports</th>
			</tr>
			</thead>
		</table>
	</content>
</g:applyLayout>

grails-app/views/report/view.gsp
<g:applyLayout name="one-column-top-nav">
	<head>
		<title>forms</title>
		<asset:javascript src="reports-manifest.js"/>
		<asset:stylesheet src="reports-manifest.css"/>
		<g:render template="/handlebars/reporting"/>
		<asset:javascript src="/reports/report-submissions-fetcher.js"/>
	</head>
	<content tag="top-nav">
		<g:render template="side-nav"/>
	</content>
	<content tag="main">
		<ol class="breadcrumb">
			<li><g:link controller="report">Report</g:link></li>
			<li class="active ">${reportInstance.name}</li>
		</ol>
		<table id="submissions-table" data-report-id="${reportInstance.id}">
			<thead>
			<tr>
				<g:each in="${reportInstance.displayColumns}" var="column">
					<th data-field="${column.question}" data-sortable="true">${column.displayName}</th>
				</g:each>
			</tr>
			</thead>
			<tbody>
			</tbody>
		</table>
	</content>
</g:applyLayout>