grails-app/controllers/com/nexusug/xlsform/FormController.groovy
package com.nexusug.xlsform

import com.nexusug.Download
import com.nexusug.xlsform.exception.XlsFormConversionException
import com.nexusug.xlsform.util.DownloadUtil
import grails.converters.JSON
import grails.transaction.Transactional

@Transactional(readOnly = true)
class FormController {

	FormStorageService formStorageService

	def index() {
		def xformList = Xform.findAllByDeleted(false, [max: 50, sort: 'lastUpdated', order: 'desc']).collect {
			[
					id         : it.id,
					name       : it.name,
					title      : it.title,
					xlsId      : it.xlsId,
					lastUpdated: g.formatDate(date: it.lastUpdated.getTime()),
					dateCreated: g.formatDate(date: it.dateCreated)
			]

		}
		def xlsFormList = XlsFormUpload.findAllByDeleted(false, [max: 50, sort: 'dateCreated', order: 'desc']).collect {
			[
					id              : it.id,
					xformTitle      : it.xform ? (it.xform.isDeleted() ? it.xform?.title + ' (deleted)' : it.xform?.title) : null,
					fileName        : it.fileName,
					dateCreated     : g.formatDate(date: it.dateCreated.getTime()),
					uploadStatus    : it.uploadStatus.name(),
					conversionReport: it.conversionReport
			]
		}

		return [xlsFormList: xlsFormList as JSON, xformList: xformList as JSON]
	}

	def view(Xform xform) {
		if (xform) {
			return [xform: xform]
		}
	}

	def downloadXlsForm(XlsFormUpload formUpload) {
		if (formUpload) {
			File xlsFile = new File(formUpload.uploadLocation)
			String fileName = formUpload.fileName
			String contentType = fileName.endsWith('xlsx') ?
					'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' : 'application/vnd.ms-excel'
			Download download = new Download(file: xlsFile, fileName: fileName, contentType: contentType)
			DownloadUtil.download(download, response)
		} else {
			flash.error = "XLSForm upload could not be found"
			redirect action: 'index'
		}
	}

	@Transactional
	def deleteXlsFormUpload(XlsFormUpload formUpload) {
		if (formUpload) {
			formUpload.deleted = true
			formUpload.save(failOnError: true)
			flash.message = "XLSForm upload successfully deleted"
		} else {
			flash.error = "XLSForm upload could not be found"
		}
		redirect action: 'index'
	}

	def downloadXform(Xform xform) {
		if (xform) {
			String fileName = "${xform.xlsId.toLowerCase()}.xml"
			Download download = new Download(content: xform.formXml, fileName: fileName, contentType: 'application/xml')
			DownloadUtil.download(download, response)
		} else {
			flash.error = "XForm could not be found"
			redirect action: 'index'
		}
	}

	@Transactional
	def deleteXform(Xform xform) {
		if (xform) {
			String originalXlsId = xform.xlsId
			xform.xlsId = xform.xlsId + '_deleted_' + System.currentTimeMillis()
			xform.deleted = true
			xform.save(failOnError: true)
			flash.message = "Xform ${originalXlsId} was successfully deleted"
		} else {
			flash.error = "specified Xform could not be found"
		}
		redirect action: 'index'
	}

	@Transactional
	def update(XlsFormUploadCommand formUpload) {
		Xform xform = Xform.get(formUpload.xformId)
		if (formUpload.validate()) {
			try {
				xform = formStorageService.createOrUpdateXform(formUpload, xform)
				if (xform.hasErrors()) {
					flash.errors = xform.errors.collect { g.message(error: it).toString() }
				} else {
					flash.message = "xform successfully updated"
				}
			} catch (XlsFormConversionException exception) {
				flash.error = exception.message
			}
			redirect action: 'view', id: xform.id
		} else {
			List<String> errors = formUpload.errors.collect { g.message(error: it).toString() }
			flash.errors = errors
			redirect action: 'view', id: xform.id
		}
	}

	@Transactional
	def upload(XlsFormUploadCommand formUpload) {
		if (formUpload.validate()) {
			try {
				Xform xform = formStorageService.createOrUpdateXform(formUpload)
				if (xform.hasErrors()) {
					flash.errors = xform.errors.collect { g.message(error: it).toString() }
				} else {
					flash.message = "xform successfully created"
				}
			} catch (XlsFormConversionException exception) {
				flash.error = exception.message
			}
			redirect action: 'index'
		} else {
			List<String> errors = formUpload.errors.collect { g.message(error: it).toString() }
			flash.errors = errors
			redirect action: 'index'
		}
	}
}

grails-app/views/form/index.gsp
<g:applyLayout name="one-column-top-nav">
	<head>
		<title>forms</title>
		<asset:javascript src="forms-manifest"/>
		<asset:stylesheet src="forms-manifest"/>
		<g:render template="/handlebars/forms"/>
	</head>
	<content tag="main">
		<div class="panel panel-default">
			<div class="panel-body">
				<span class="lead">
					Browse and import an XLSForm</span>
				<a href="#" data-toggle="popover" data-trigger="hover|click" data-html="true"
				   data-content="<p><em>XLSForm is a form standard created to help simplify the authoring of forms
					   in Excel.</em></p>
					   <a class='btn btn-default btn-xs btn-block' target='_blank'
					   href='http://xlsform.org/'>creating XLSForms</a>

					   <a class='btn btn-default btn-xs btn-block' target='_blank'
					   href='http://bit.ly/2pWr2Od'>sample XLSForm</a>">
					<i class="fa fa-question-circle small"></i></a>
				<div class="divider15"></div>

				<g:uploadForm name="xlsForm" action="upload">
					<div class="form-group">
						<input type="file" class="file-loading" name="uploadFile" id="uploadFile"
							   data-allowed-file-extensions='["xls", "xlsx"]'/>
					</div>
				</g:uploadForm>
			</div>
		</div>

		<div class="panel panel-default">
			<div class="panel-heading">
				Available xforms
			</div>
			<div class="panel-body">
				<table id="xform-list" data-striped="true" data-detail-view="true" data-data="${xformList}">
					<thead>
					<tr>
						<th data-field="title"><g:message code="form.title"/></th>
						<th data-field="name"><g:message code="form.name"/></th>
						<th data-field="xlsId" data-field="formId"><g:message code="form.xlsId"/></th>
						<th data-field="lastUpdated"><g:message code="form.last_update"/></th>
					</tr>
					</thead>
				</table>
			</div>
		</div>

		<div class="panel panel-default">
			<div class="panel-heading text-capitalize">recently imported XLSForms</div>

			<div class="panel-body">
				<table id="xls-form-list" data-striped="true" data-detail-view="true" data-data="${xlsFormList}">
					<thead>
					<tr>
						<th data-field="fileName">File name</th>
						<th data-field="dateCreated">Date of import</th>
						<th data-field="uploadStatus">Status</th>
					</tr>
					</thead>
				</table>
			</div>
		</div>
	</content>
</g:applyLayout>

grails-app/views/form/view.gsp
<g:applyLayout name="one-column-top-nav">
	<head>
		<title>forms</title>
		<asset:javascript src="forms-manifest"/>
		<asset:stylesheet src="forms-manifest"/>
		<g:render template="/handlebars/forms"/>
	</head>
	<content tag="main">
		<ol class="breadcrumb">
			<li><g:link controller="form">Forms</g:link></li>
			<li class="active">${xform.name}</li>
		</ol>

		<div class="page-header">
			<h4 class="text-capitalize">${xform.title}</h4>
		</div>

		<div class="panel panel-default">
			<div class="panel-body">
				<p class="lead">Browse and import an XLSForm to update xform</p>
				<g:uploadForm name="xlsForm" action="update">
					<div class="form-group">
						<input type="file" class="file-loading" name="uploadFile" id="uploadFile"
							   data-allowed-file-extensions='["xls", "xlsx"]'/>
					</div>
					<input type="hidden" name="xformId" id="xformId" value="${xform.id}">
				</g:uploadForm>
			</div>
		</div>

		<div>
			<a href="${g.createLink(controller: 'data', action: 'submissions', id: xform.xlsId)}"
			   class="btn btn-default">view submissions</a>
			<a href="${g.createLink(controller: 'data', action: 'capture', id: xform.xlsId)}"
			   class="btn btn-default">capture data</a>
		</div>
	</content>
</g:applyLayout>