grails-app/controllers/com/nexusug/xlsform/DataController.groovy
package com.nexusug.xlsform

import com.nexusug.xlsform.display.model.XformDisplayModel
import com.nexusug.xlsform.display.util.XformReaderEditUtils
import com.nexusug.xlsform.display.util.XformReader
import com.nexusug.xlsform.exception.InvalidSubmission
import com.nexusug.xlsform.exception.XformNotFoundException
import grails.transaction.Transactional
import groovy.json.JsonBuilder
import org.codehaus.groovy.grails.plugins.web.api.MimeTypesApiSupport
import org.springframework.http.HttpStatus

import static org.springframework.http.HttpStatus.*

@Transactional(readOnly = true)
class DataController {
	static allowedMethods = [save: 'POST']

	private MimeTypesApiSupport apiSupport = new MimeTypesApiSupport()

	DataService dataService

	def index() {
		List<XformSubmission> submissions = dataService.getSubmissions([max: 20])
		List<Xform> formList = Xform.all
		[mostRecentSubmissions: submissions, formList: formList]
	}

	def viewFormSubmissions(String id) {
		redirect action: 'submissions', id: id
	}

	def submissions(String id) {
		if (!id) {
			flash.warn = "No form provided"
			redirect action: 'index'
			return
		}
		Xform form = Xform.findByXlsId(id)
		if (!form) {
			flash.error = "Could not find form with xlsId: ${id}"
			redirect action: 'index'
			return
		}
		List<XformSubmission> submissions = dataService.getSubmissions(id)

		[submissions: submissions, xform: form]
	}

	def captureFormData(String id) {
		redirect action: 'capture', id: id
	}

	def capture() {
		String formId = params.id
		if (!formId) {
			redirect action: 'index'
			return
		}

		Xform form = Xform.findByXlsId(formId)
		if (!form) {
			flash.error = "Could not find find form with id: ${formId}"
			redirect action: 'index'
			return
		}

		XformDisplayModel xformDisplayModel = new XformDisplayModel()
		xformDisplayModel.name = form.name
		xformDisplayModel.title = form.title
		xformDisplayModel.xlsId = form.xlsId
		xformDisplayModel.xformId = form.id
		xformDisplayModel.displayables = XformReader.getFormElements(form.formXml)
		String xformModelJson = XformReader.serializeFormModelToJSON(form.formXml)

		[
				xformModelJson       : xformModelJson,
				xformDisplayModel    : xformDisplayModel,
				xformDisplayModelJson: new JsonBuilder(xformDisplayModel).toPrettyString()
		]
	}

	def edit(long id) {
		XformSubmission submission = XformSubmission.get(id)
		Xform xform = submission.xform

		XformDisplayModel xformDisplayModel = new XformDisplayModel()
		xformDisplayModel.name = xform.name
		xformDisplayModel.title = xform.title
		xformDisplayModel.xlsId = xform.xlsId
		xformDisplayModel.displayables = XformReaderEditUtils.getFormElements(xform.formXml, submission)
		String xformModelJson = XformReader.serializeFormModelToJSON(xform.formXml)

		[
				submission           : submission,
				xformModelJson       : xformModelJson,
				xformDisplayModel    : xformDisplayModel,
				xformDisplayModelJson: new JsonBuilder(xformDisplayModel).toPrettyString()
		]
	}

	@Transactional
	def update() {
		apiSupport.withFormat(request) {
			'json' {
				Map payload = request.getJSON()
				dataService.updateSubmission(payload)
				render status: ACCEPTED
			}
			'*' {
				render status: UNSUPPORTED_MEDIA_TYPE
			}
		}
	}

	@Transactional
	def save() {
		apiSupport.withFormat(request) {
			'json' {
				Map payload = request.getJSON()
				dataService.captureJsonSubmission(payload)
				render status: CREATED
			}
			'xml' {
				String payload = request.reader.text
				dataService.captureXMLSubmission(payload)
				render status: CREATED
			}
			'*' {
				render status: UNSUPPORTED_MEDIA_TYPE
			}
		}
	}

	@Transactional
	def delete(XformSubmission submission) {
		if (submission == null) {
			notFound()
			return
		}
		submission.archived = true
		submission.save(failOnError: true, flush: true)
		withFormat {
			html {
				flash.message = g.message(code: 'submission.deleted.message')
				redirect action: 'index'
			}
			'*' {
				render status: OK
			}
		}
	}

	def handleXformNotFoundException(XformNotFoundException exception) {
		handleError(exception.message, BAD_REQUEST)
	}

	def handleInvalidSubmission(InvalidSubmission exception) {
		handleError(exception.message, BAD_REQUEST)
	}

	private void handleError(String message, HttpStatus status) {
		withFormat {
			'json' {
				render text: message, status: status, contentType: 'application/json'
			}
			'xml' {
				render text: message, status: status, contentType: 'application/xml'
			}
			'*' {
				render text: message, status: status
			}
		}
	}

	protected void notFound() {
		//todo this doesn't seem to work, needs to be fixed
		withFormat {
			html {
				flash.message = message(code: 'default.not.found.message', args: [
						message(code: 'submission.label', default: 'submission'),
						params.id
				])
				redirect action: "index"
			}
			'*' { render status: NOT_FOUND }
		}
	}
}

grails-app/views/data/_submissions_table.gsp
<table data-toggle="table" data-striped="true">
	<thead>
	<tr>
		<th>form id</th>
		<th>form title</th>
		<th>upload date</th>
		<th></th>
	</tr>
	</thead>
	<tbody>
	<g:each in="${submissions}" var="submission">
		<tr>
			<td>${submission.xform.xlsId}</td>
			<td>${submission.xform.title}</td>
			<td><g:formatDate date="${submission.dateCreated}"/></td>
			<td>
				<g:link class="btn btn-default btn-sm btn-danger" controller="data"
						action="delete" id="${submission.id}" title="delete submission"
						data-toggle="confirm-delete-submission">
					<i class="fa fa-trash"></i>
				</g:link>
				<g:link class="btn btn-default btn-sm" controller="data" action="edit" id="${submission.id}"
						title="edit submission">
					<i class="fa fa-edit"></i>
				</g:link>
			</td>
		</tr>
	</g:each>
	</tbody>
</table>

grails-app/views/data/capture.gsp
<g:applyLayout name="one-column-top-nav">
	<head>
		<title>forms</title>
		<asset:javascript src="xls-form/form-visualizer"></asset:javascript>
		<asset:javascript src="xls-form/form-data-capture-helper"></asset:javascript>
		<asset:javascript src="data/data-capture"></asset:javascript>
		<g:render template="/handlebars/xlsform-elements"/>
	</head>
	<content tag="main">
		<ol class="breadcrumb">
			<li><g:link controller="data">Data</g:link></li>
			<li><g:link controller="form" action="view"
						id="${xformDisplayModel.xformId}">${xformDisplayModel.xlsId}</g:link></li>
			<li class="active">capture data</li>
		</ol>
		<g:form action="save" name="data-capture-form">
			<g:render template="/formVisualizer/form_visualization"
					  model="${[
							  xformDisplayModel    : xformDisplayModel,
							  xformDisplayModelJson: xformDisplayModelJson,
							  xformModelJson       : xformModelJson]}"/>
		</g:form>
	</content>
</g:applyLayout>

grails-app/views/data/edit.gsp
<g:applyLayout name="one-column-top-nav">
	<head>
		<title>Data edit</title>
		<g:if test="${xformDisplayModel}">
			<asset:javascript src="xls-form/form-visualizer"></asset:javascript>
			<asset:javascript src="xls-form/form-data-capture-helper"></asset:javascript>
			<asset:javascript src="data/data-edit"></asset:javascript>
			<g:render template="/handlebars/xlsform-elements"/>
		</g:if>
	</head>
	<content tag="main">
		<ol class="breadcrumb">
			<li><g:link controller="data">Data</g:link></li>
			<li><g:link controller="data" action="submissions" id="${xformDisplayModel.xlsId}">${xformDisplayModel.xlsId}</g:link></li>
			<li class="active ">edit submission</li>
		</ol>
		<input type="hidden" id="edit-form-xls-id" value="${xformDisplayModel.xlsId}"/>
		<g:form action="update" name="data-capture-form">
			<input type="hidden" name="submissionId" value="${submission.id}">
			<g:render template="/formVisualizer/form_visualization"/>
		</g:form>
	</content>
</g:applyLayout>

grails-app/views/data/index.gsp
<g:applyLayout name="one-column-top-nav">
	<head>
		<title>forms</title>
	</head>
	<content tag="top-nav">
		<asset:javascript src="data-manifest"/>
		<asset:javascript src="data/submissions-management"/>
		<asset:stylesheet src="data-manifest"/>
	</content>
	<content tag="main">
		<div class="panel panel-default">
			<div class="panel-body">
				<g:form controller="data">
					<div class="form-group">
						<select class="form-control" name="id" id="form-xlsId">
							<g:each in="${formList}" var="form">
								<option value="${form.xlsId}">${form.title}</option>
							</g:each>
						</select>
					</div>

					<div class="form-group">
						<g:actionSubmit class="btn btn-default btn-sm" value="view submissions" action="viewFormSubmissions" />
						<g:actionSubmit class="btn btn-default btn-sm" value="capture data" action="captureFormData" />
					</div>
				</g:form>
			</div>
		</div>

		<div class="panel panel-default">
			<div class="panel-heading text-capitalize">recently captured data</div>

			<div class="panel-body">
				<g:set var="submissions" value="${mostRecentSubmissions}"/>
				<g:render template="submissions_table" model="${submissions}"/>
			</div>
		</div>
	</content>
</g:applyLayout>

grails-app/views/data/submissions.gsp
<g:applyLayout name="one-column-top-nav">
	<head>
		<title>forms</title>
		<asset:javascript src="data-manifest"/>
		<asset:stylesheet src="data-manifest"/>
	</head>
	<content tag="main">
		<ol class="breadcrumb">
			<li><g:link controller="data">Data</g:link></li>
			<li><g:link controller="form" action="view" id="${xform.id}">${xform.xlsId}</g:link></li>
			<li class="active">submissions</li>
		</ol>


		<g:render template="submissions_table" model="${[submissions: submissions]}"/>
	</content>
</g:applyLayout>